# Video "What is TensorFlow"

In [0]:
%config IPCompleter.greedy=True

In [2]:
import tensorflow as tf
import numpy as np
print(tf.__version__)

1.15.0-rc3


In [0]:
tf.reset_default_graph()
a = tf.placeholder(np.float32, (2, 2))
b = tf.Variable(tf.ones((2, 2)))
c = a @ b

In [4]:
print(c)

Tensor("matmul:0", shape=(2, 2), dtype=float32)


In [0]:
s = tf.InteractiveSession()

In [6]:
# Другой способ (его не было в изначальном ноутбуке)
s.run(tf.global_variables_initializer())
c.eval({a: np.ones((2, 2))})

array([[2., 2.],
       [2., 2.]], dtype=float32)

In [7]:
s.run(tf.global_variables_initializer())
s.run(c, feed_dict={a: np.ones((2, 2))})

array([[2., 2.],
       [2., 2.]], dtype=float32)

In [0]:
s.close()

# Video "Our first model in TensorFlow"

### Simple optimization (with simple prints)

In [0]:
tf.reset_default_graph()
# Разницы между get_variable и variable по сути нет
x = tf.get_variable("x", shape=())
f = x ** 2

In [10]:
optimizer = tf.train.GradientDescentOptimizer(0.1)
step = optimizer.minimize(f, var_list=[x])

Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where


In [11]:
tf.trainable_variables()

[<tf.Variable 'x:0' shape=() dtype=float32_ref>]

In [12]:
with tf.Session() as s:  # in this way session will be closed automatically
    s.run(tf.global_variables_initializer())
    for i in range(10):
        _, curr_x, curr_f = s.run([step, x, f])
        print(curr_x, curr_f)

-1.1887691 2.208081
-0.9510153 1.413172
-0.7608122 0.9044301
-0.6086498 0.57883525
-0.48691982 0.37045458
-0.38953584 0.23709092
-0.31162867 0.15173817
-0.24930294 0.097112425
-0.19944236 0.062151954
-0.15955389 0.039777253


In [13]:
# А теперь пример как сделать то же самое, но вместо get_variable использовать Variable. Тут нужно начально значение
with tf.Session() as s:
    x = tf.Variable(initial_value=4.0)
    f = x ** 2

    s.run(tf.global_variables_initializer())
    optimizer = tf.train.GradientDescentOptimizer(0.1)
    step = optimizer.minimize(f, var_list=[x])

    for _ in range(25):
        a, b, c = s.run([step, x, f])
        print(a, b, c)

None 3.2 16.0
None 2.56 10.240001
None 2.0479999 6.5536
None 1.6383998 4.1943035
None 1.3107198 2.684354
None 1.0485759 1.7179865
None 0.8388607 1.0995114
None 0.6710886 0.70368725
None 0.53687084 0.45035988
None 0.42949668 0.2882303
None 0.34359735 0.18446739
None 0.27487788 0.11805914
None 0.2199023 0.07555785
None 0.17592184 0.048357025
None 0.14073747 0.030948495
None 0.11258998 0.019807037
None 0.09007198 0.0126765035
None 0.07205759 0.008112962
None 0.057646073 0.005192296
None 0.04611686 0.0033230698
None 0.036893487 0.0021267647
None 0.02951479 0.0013611293
None 0.023611832 0.0008711228
None 0.018889466 0.0005575186
None 0.015111573 0.00035681194


### Simple optimization (with tf.Print)

In [14]:
tf.reset_default_graph()
x = tf.get_variable("x", shape=(), dtype=tf.float32)
f = x ** 2
f = tf.Print(f, [x, f], "x, f:")

Instructions for updating:
Use tf.print instead of tf.Print. Note that tf.print returns a no-output operator that directly prints the output. Outside of defuns or eager mode, this operator will not be executed unless it is directly specified in session.run or used as a control dependency for other operators. This is only a concern in graph mode. Below is an example of how to ensure tf.print executes in graph mode:



In [0]:
optimizer = tf.train.GradientDescentOptimizer(0.1)
step = optimizer.minimize(f)

In [0]:
with tf.Session() as s:
    s.run(tf.global_variables_initializer())
    for i in range(10):
        s.run([step, f])

In [0]:
# Prints to jupyter server stdout (not available in Coursera Notebooks):
# 2018-07-21 18:01:27.308270: I tensorflow/core/kernels/logging_ops.cc:79] x, f:[-1.0670249][1.1385423]
# 2018-07-21 18:01:27.308809: I tensorflow/core/kernels/logging_ops.cc:79] x, f:[-0.85361993][0.72866696]
# 2018-07-21 18:01:27.309116: I tensorflow/core/kernels/logging_ops.cc:79] x, f:[-0.68289596][0.46634689]
# 2018-07-21 18:01:27.309388: I tensorflow/core/kernels/logging_ops.cc:79] x, f:[-0.54631674][0.29846197]
# 2018-07-21 18:01:27.309678: I tensorflow/core/kernels/logging_ops.cc:79] x, f:[-0.43705338][0.19101566]
# 2018-07-21 18:01:27.309889: I tensorflow/core/kernels/logging_ops.cc:79] x, f:[-0.34964269][0.12225001]
# 2018-07-21 18:01:27.310213: I tensorflow/core/kernels/logging_ops.cc:79] x, f:[-0.27971417][0.078240015]
# 2018-07-21 18:01:27.310475: I tensorflow/core/kernels/logging_ops.cc:79] x, f:[-0.22377133][0.050073609]
# 2018-07-21 18:01:27.310751: I tensorflow/core/kernels/logging_ops.cc:79] x, f:[-0.17901707][0.032047112]
# 2018-07-21 18:01:27.310963: I tensorflow/core/kernels/logging_ops.cc:79] x, f:[-0.14321366][0.020510152]

### Simple optimization (with TensorBoard logging)

In [0]:
tf.reset_default_graph()
x = tf.get_variable("x", shape=(), dtype=tf.float32)
f = x ** 2

In [0]:
optimizer = tf.train.GradientDescentOptimizer(0.1)
step = optimizer.minimize(f)

In [0]:
tf.summary.scalar('curr_x', x)
tf.summary.scalar('curr_f', f)
summaries = tf.summary.merge_all()

In [0]:
s = tf.InteractiveSession()
summary_writer = tf.summary.FileWriter("logs/1", s.graph)
s.run(tf.global_variables_initializer())
for i in range(10):
    _, curr_summaries = s.run([step, summaries])
    summary_writer.add_summary(curr_summaries, i)
    summary_writer.flush()

Run  `tensorboard --logdir=./logs` in bash

This is what you can see in your browser **(not available in Coursera Notebooks)**
<img src="images/TensorBoard.jpg" style="width:70%">

**If you're running on Google Colab you can still run TensorBoard!**

In [0]:
# !!! RUN THIS CELL ONLY ON GOOGLE COLAB !!!
! wget https://raw.githubusercontent.com/hse-aml/intro-to-dl/master/setup_google_colab.py -O setup_google_colab.py
import setup_google_colab

# run tensorboard in background
import os
os.system("tensorboard --logdir=./logs --host 0.0.0.0 --port 6006 &")

# expose port and show the link
setup_google_colab.expose_port_on_colab(6006)

--2019-01-09 12:08:46--  https://raw.githubusercontent.com/hse-aml/intro-to-dl/master/setup_google_colab.py
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.248.133
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.248.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 3792 (3.7K) [text/plain]
Saving to: ‘setup_google_colab.py’

setup_google_colab. 100%[=====================>]   3.70K  --.-KB/s   in 0s     

2019-01-09 12:08:46 (45.2 MB/s) - ‘setup_google_colab.py’ saved [3792/3792]



CalledProcessError: Command 'netstat -vatn' returned non-zero exit status 127.

In [0]:
s.close()

### Training a linear model

In [23]:
# generate model data
N = 1000
D = 3
x = np.random.random((N, D))
w = np.random.random((D, 1))
y = x @ w + np.random.randn(N, 1) * 0.20

print(x.shape, y.shape)
print(w.T)

(1000, 3) (1000, 1)
[[0.317239   0.61950684 0.97055912]]


In [33]:
tf.reset_default_graph()

features = tf.placeholder(tf.float32, shape=(None, D))
target = tf.placeholder(tf.float32, shape=(None, 1))

weights = tf.get_variable("weights", shape=(D, 1), dtype=tf.float32)
predictions = features @ weights

loss = tf.reduce_mean((target - predictions) ** 2)

print(target.shape, predictions.shape, loss.shape)

(?, 1) (?, 1) ()


In [0]:
optimizer = tf.train.GradientDescentOptimizer(0.1)
step = optimizer.minimize(loss)

In [35]:
with tf.Session() as s:
    s.run(tf.global_variables_initializer())
    for i in range(300):
        
        _, curr_loss, curr_weights = s.run([step, loss, weights], 
                                           feed_dict={features: x, target: y})
        if i % 50 == 0:
            print(curr_loss)

1.2035939
0.050302397
0.042055916
0.040528495
0.040245324
0.04019278


In [27]:
# found weights
curr_weights.T

array([[0.3319966 , 0.6075085 , 0.97480315]], dtype=float32)

In [28]:
# true weights
w.T

array([[0.317239  , 0.61950684, 0.97055912]])

## Or same example but using tf.Variable:

In [36]:
tf.reset_default_graph()

features = tf.Variable(dtype=tf.float32, initial_value=x)
target = tf.Variable(dtype=tf.float32, initial_value=y)

weights = tf.get_variable("weights", shape=(D, 1), dtype=tf.float32)
predictions = features @ weights

loss = tf.reduce_mean((target - predictions) ** 2)

print(target.shape, predictions.shape, loss.shape)

(1000, 1) (1000, 1) ()


In [0]:
optimizer = tf.train.GradientDescentOptimizer(0.1)
step = optimizer.minimize(loss)

In [38]:
with tf.Session() as s:
    s.run(tf.global_variables_initializer())
    for i in range(300):
        
        _, curr_loss, curr_weights = s.run([step, loss, weights])
        if i % 50 == 0:
            print(curr_loss)

1.8104385
0.040672697
0.037056085
0.03498909
0.033270206
0.031677354
